language: node_js
dist: xenial
services:
  - redis-server
addons:
  apt:
    packages:
    - rabbitmq-server 
node_js:
  - node
  - 12
go:
  - 1.14.x 
before_install:
   - wget  https://github.com/nats-io/nats-server/releases/download/v2.0.0/nats-server-v2.0.0-linux-amd64.zip
   - nats-server-v2.0.0-linux-amd64/nats-server </dev/null &>/dev/null &
before_script:
  - sleep 30
